# Generated by Django 5.0.6 on 2024-07-19 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('project_a', models.TextField()),
                ('project_b', models.TextField()),
                ('filename_a', models.TextField()),
                ('filename_b', models.TextField()),
                ('content_a', models.TextField()),
                ('content_b', models.TextField()),
            ],
            options={
                'ordering': ['sequence', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.SlugField(unique=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('responded_on', models.DateTimeField()),
                ('value', models.CharField(choices=[('A', 'A'), ('SA', 'Strong A'), ('WA', 'Weak A'), ('B', 'B'), ('SB', 'Strong B'), ('WB', 'Weak B'), ('E', 'Equivalent'), ('U', 'Unsure')], max_length=2)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileranker.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-responded_on'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileranker.sequence'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_response'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('sequence', 'position'), name='unique_position_per_sequence'),
        ),
    ]
