# Generated by Django 5.0.6 on 2024-07-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileranker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='seed',
        ),
        migrations.AddField(
            model_name='file',
            name='entities',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='lloc',
            field=models.IntegerField(null=True),
        ),
    ]
