# Generated by Django 5.0.6 on 2024-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileranker', '0002_remove_sequence_seed_file_entities_file_lloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='commits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='value',
            field=models.CharField(choices=[('SA', 'Strong A'), ('WA', 'Weak A'), ('SB', 'Strong B'), ('WB', 'Weak B'), ('E', 'Equivalent'), ('U', 'Unsure')], max_length=2),
        ),
    ]
